journalist_task:
  description: >
    Obtain information from youtube videos to write articles of a newspaper.
    With this information, compile a list of the videos that you found.
    USE JUST ONCE THE TOOL PROVIDED, IT DOESN'T NEED AN INPUT.
    
    Do the following things with the information obtained:
    - You MUST write in SPANISH.
    - Rewrite the title of the video to make it more engaging and interesting for the readers of the newspaper.
    - Rewrite the text of the video to make it more engaging and interesting for the readers of the newspaper(if needed).
    - Include the author of the video.
    - Include the date of the video in this format "Day of Month of Year".
    - Include the URL of the video.

  expected_output: >
    A markdown document in SPANISH with the complete information obtained about the videos.
    
    Each one should contain:
    - Title:
    - Date:
    - Text: 
    - Source: [URL of the video]

    Here is an example of a document that you are expected to produce:
    <EXAMPLE>
    
      - **Title:** La deuda pública española es mucho más alta de lo que se cree
        **Date:** 25 de Julio de 2024
        **Text:** La deuda pública española es mucho más alta de lo que se cree. Si se incluyera la cantidad de dinero que se debe a los futuros pensionistas, la cifra actual de alrededor del 110% del PIB se multiplicaría por cinco. Según Eurostat, el valor presente de los gastos futuros en pensiones comprometidos por el Estado español asciende a un alarmante 500% del PIB, lo que lo convierte en el país europeo con mayor deuda implícita en materia de pensiones. Esta deuda implícita puede llevar a una visión distorsionada de la situación económica real del país. Aunque no se refleja en las estadísticas oficiales de deuda pública, es un pasivo importante que el Estado español tendrá que enfrentar en el futuro. Sin embargo, es importante tener en cuenta que el Estado puede recortar las pensiones en el futuro para hacer frente a esta deuda implícita. Es probable que en las próximas décadas se produzcan recortes en las pensiones futuras que hoy el estado se ha comprometido a pagar. Esto significa que muchas personas que contaban con recibir un determinado nivel de ingresos a través del sistema público de pensiones van a ver defraudadas sus expectativas. Por lo tanto, es prudente anticipar la posibilidad de que nuestras pensiones futuras vayan a ser recortadas y planificar financieramente nuestro futuro de manera adecuada. Para ilustrar la magnitud del problema, si consideramos que el Estado tendría que destinar la recaudación equivalente a 14 años de ingresos públicos para hacer frente a todos los pasivos del Estado, es evidente que la deuda pública en forma de derechos pensionales es un tema que requiere atención urgente. Una forma de preparar nuestro futuro es ahorrando periódicamente a través de una plataforma como Trade Republic, que nos permite invertir en índices bursátiles globales con rentabilidades históricas de alrededor del 6 o 7% al año. De esta manera, podemos complementar nuestras pensiones públicas con una pensión privada y asegurar un futuro financiero más seguro.
        **Source:** ["Title of the video"](https://www.youtube.com/watch?v=Qs6BdBHiLwM&ab_channel=JuanRam%C3%B3nRallo) por Author

        [... more news articles ...]

    </EXAMPLE>

editor_task:
  description: >
    Fill the following HTML template with exactly the same information that is given to you.
    
    Follow these rules:
    - Do not truncate the information or change the order of the elements. 
    - Do not modify the content of the news articles.
    - Do not add any additional information to the newspaper.
    - Add ALL the news articles provided to the newspaper. Even if the template only shows one news articles, you should include all the news articles provided as context using the format provided in the template.

    {html_template}
  expected_output: >
    Return ONLY the contents of the HTML template, without any tripple quotes like '```', '```html' or any other text. 
    This output will be saved as a HTML file and sent to the subscribers.